[project]
name = 'Intellectual-Property-Licensing'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.ip-registration-trait]
path = 'contracts/ip-registration-trait.clar'
clarity_version = 2
epoch = 2.5

[contracts.license-terms-trait]
path = 'contracts/license-terms-trait.clar'
clarity_version = 2
epoch = 2.5

[contracts.usage-tracking-trait]
path = 'contracts/usage-tracking-trait.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
